ivpn/android-app

- CHANGELOG.md
We need to include the SHA1 hashes and download links in our CHANGELOG.md file.
> Task/DRD-392 Add hashes and download links in CHANGELOG.md

- CHANGELOG.md
> Fix line break in the Changelog file

- CHANGELOG.md
> Line breaking for Changelog part 2

- app/src/main/java/net/ivpn/client/ui/mocklocation/MockLocationController.kt
> [GAA-43] Fix mock location crash for Android 10

- app/build.gradle
- app/src/main/java/net/ivpn/client/common/utils/ComponentUtil.java
- app/src/main/java/net/ivpn/client/v2/MainActivity.kt
- app/src/main/java/net/ivpn/client/v2/antitracker/AntiTrackerFragment.kt
- build.gradle
> [GAA-46]fix Sentry

- app/src/main/java/net/ivpn/client/common/session/SessionController.kt
- app/src/main/java/net/ivpn/client/common/utils/ComponentUtil.java
- app/src/main/java/net/ivpn/client/v2/killswitch/KillSwitchFragment.kt
- app/src/main/java/net/ivpn/client/v2/network/NetworkViewModel.kt
- app/src/main/java/net/ivpn/client/vpn/local/KillSwitchService.java
- app/src/main/java/net/ivpn/client/vpn/local/WifiWatcherService.java
> [GAA-48] Fix notification issue after log out

- app/build.gradle
> Revert build version for F-Droid release

- .gitignore
- fdroid/build.gradle
- site/build.gradle
- store/src/main/java/net/ivpn/client/signup/SignUpViewModel.kt
> Update build versions for all submodules

- .gitignore
- build.gradle
- core/build.gradle
- core/src/main/AndroidManifest.xml
- fdroid/build.gradle
- site/build.gradle
> Remove libs from gradle file

- core/build.gradle
- core/src/main/java/net/ivpn/core/v2/connect/ConnectFragment.kt
- core/src/main/java/net/ivpn/core/v2/connect/MapDialogs.kt
- core/src/main/java/net/ivpn/core/v2/viewmodel/AntiTrackerViewModel.kt
- core/src/main/java/net/ivpn/core/v2/viewmodel/ConnectionViewModel.kt
- core/src/main/res/layout/view_sliding_panel.xml
- core/src/main/res/values/strings.xml
- fdroid/build.gradle
- site/build.gradle
- store/build.gradle
> [GAA-23] fix popup appearing on wrong fragment. Fix build

- core/src/main/assets/servers.json
- core/src/main/java/de/blinkt/openvpn/core/Connection.java
- core/src/main/java/net/ivpn/core/common/bindings/SpinnerBindingAdapter.java
- core/src/main/java/net/ivpn/core/rest/IVPNApi.java
- core/src/main/java/net/ivpn/core/rest/data/model/Server.java
- core/src/main/java/net/ivpn/core/v2/protocol/ProtocolFragment.kt
- core/src/main/java/net/ivpn/core/v2/protocol/port/Port.java
- core/src/main/java/net/ivpn/core/v2/protocol/port/PortAdapter.java
- core/src/main/java/net/ivpn/core/v2/viewmodel/ProtocolViewModel.java
- core/src/main/java/net/ivpn/core/vpn/openvpn/ProfileManager.java
- core/src/main/res/layout/protocol_openvpn_section_settings.xml
- core/src/main/res/layout/protocol_wireguard_section_settings.xml
- core/src/main/res/layout/view_sliding_panel.xml
- core/src/main/res/values/strings.xml
> Port-based MultiHop for OpenVPN

- core/src/main/res/values/strings.xml
> Incorrect Multi-hop text on Protocol screen

- core/src/main/java/net/ivpn/core/v2/protocol/port/Port.java
> Add new ports

- store/src/main/java/net/ivpn/client/billing/Utils.java
> Missing space between words in the "Add funds" screen

- README.md
> Error in the readme dependencies

- .github/workflows/build.yml
- .github/workflows/codeql.yml
> Add Gradle Wrapper Validation

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- core/src/main/assets/servers.json
> Label of the new South African server is missing in the map

- core/src/main/java/net/ivpn/core/v2/viewmodel/SplitTunnelingViewModel.java
> TransactionTooLargeException

- core/src/main/java/net/ivpn/core/rest/data/model/Server.java
> Server.getIpAddress NullPointerException

- core/src/main/java/net/ivpn/core/v2/account/AccountFragment.kt
> AccountFragment.onLogOut IllegalStateException

- store/src/main/java/net/ivpn/client/signup/SignUpViewModel.kt
> SignUpViewModel.openSite AndroidRuntimeException

- store/src/main/java/net/ivpn/client/billing/BillingManagerWrapper.java
> InitialPaymentRequestBody NullPointerException

- core/src/main/java/net/ivpn/core/common/pinger/PingDataSet.kt
- core/src/main/java/net/ivpn/core/common/pinger/PingProvider.kt
- core/src/main/java/net/ivpn/core/v2/viewmodel/ConnectionViewModel.kt
> Servers ping information not updated when disconnecting from the VPN

- .github/CONTRIBUTING.md
> Add Public Beta section in Contributing docs

- core/build.gradle
- site/build.gradle
- store/build.gradle
> Change target API level to 31

- core/build.gradle
- core/tools/libwg-go/Makefile
- fdroid/build.gradle
- site/build.gradle
- store/build.gradle
> v2.8.4 build

- .github/workflows/validate-gradle-wrapper.yaml
This action validates the checksums of [Gradle Wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) JAR files present in the source tree and fails if unknown Gradle Wrapper JAR files are found.
> Add validate-gradle-wrapper.yaml

- CHANGELOG.md
- core/src/main/res/values-night/styles.xml
- core/src/main/res/values/styles.xml
Resolves #157
Resolves #173
Resolves #217
> Screen shows bright white background on launch with dark mode

- core/src/main/java/net/ivpn/core/common/prefs/ServersPreference.kt
- core/src/main/java/net/ivpn/core/common/prefs/ServersRepository.kt
Resolves #120
Resolves #59
Resolves #199
> Servers change randomly when switching protocols

- core/src/main/java/net/ivpn/core/rest/data/model/Server.java
> Server.getIpAddresses NullPointerException

- store/src/main/java/net/ivpn/client/billing/BillingManagerWrapper.java
> BillingManagerWrapper.initialPayment NullPointerException

- core/src/main/java/net/ivpn/core/v2/serverlist/all/AllServersRecyclerViewAdapter.kt
> AllServersRecyclerViewAdapter.onChangeState ArrayIndexOutOfBoundsException

- core/src/main/java/de/blinkt/openvpn/core/Connection.java
> Connect to OpenVPN gateway using IP address

- core/src/main/java/net/ivpn/core/common/prefs/EncryptedSettingsPreference.kt
- core/src/main/java/net/ivpn/core/common/prefs/ServersRepository.kt
- core/src/main/java/net/ivpn/core/common/prefs/Settings.kt
- core/src/main/java/net/ivpn/core/rest/data/model/AntiTracker.java
> Internet blocked when using OpenVPN + MultiHop + AnTitracker

- fdroid/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
- fdroid/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
- site/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
- site/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
- store/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
- store/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
> Android 13 themed icon

- README.md
Add [Accrescent](https://accrescent.app/) as way to download IVPN for Android, along with Play Store & F-Droid
The README currently doesn't list Accrescent as an app "store".
The README will display a link to the Accrescent link for IVPN.  (Currently Accrescent doesn't generate browser-readable app pages and will redirect by default to its 404 Not Found [page](https://accrescent.app/whoops).)
N/A
> Add Accrescent to README.md

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/validate-gradle-wrapper.yaml
> Update CI workflows

- core/src/main/res/values-night/styles.xml
- core/src/main/res/values/styles.xml
> Nav bar theme color

- core/src/main/res/layout/apps_search_item.xml
- core/src/main/res/layout/search_item.xml
> Update search field placeholders

- core/src/main/java/net/ivpn/core/v2/connect/ConnectFragment.kt
> IPv6 label briefly shown on OpenVPN servers

- core/src/main/java/net/ivpn/core/v2/updates/UpdatesController.kt
- core/src/main/res/layout/settings_section_about.xml
- core/src/main/res/values/strings.xml
- fdroid/src/main/java/net/ivpn/client/updates/StubUpdatesViewModel.kt
- site/src/main/java/net/ivpn/client/updates/UpdatesViewModel.kt
- store/src/main/java/net/ivpn/client/updates/UpdatesStubViewModel.kt
> Include the app's version number

- core/src/main/res/layout/content_wireguard_details.xml
- core/src/main/res/layout/protocol_openvpn_section_settings.xml
- core/src/main/res/layout/protocol_wireguard_section_settings.xml
> Increase tap area for Settings buttons/actions

- core/src/main/assets/servers.json
> Missing location labels

- core/src/main/java/net/ivpn/core/common/prefs/ServersRepository.kt
- core/src/main/java/net/ivpn/core/v2/viewmodel/LocationViewModel.kt
> Missing locations on map

- core/src/main/java/net/ivpn/core/common/Constant.java
> Remove CDN from UPDATE_URL

- core/build.gradle
- fdroid/build.gradle
- gradle.properties
- liboqs-android/build.gradle
- site/build.gradle
- store/build.gradle
> OpenVPN connections issues in the Android app from Accrescent

- core/build.gradle
- fdroid/build.gradle
- liboqs-android/build.gradle
- site/build.gradle
- store/build.gradle
> Change target API level to 33

- core/build.gradle
- core/src/main/AndroidManifest.xml
- core/src/main/java/net/ivpn/core/common/bindings/ImageViewSrcBindingAdapter.kt
- core/src/main/java/net/ivpn/core/v2/connect/ConnectFragment.kt
- core/src/main/java/net/ivpn/core/v2/map/MapView.kt
- core/src/main/java/net/ivpn/core/v2/map/animation/MapAnimator.kt
- fdroid/build.gradle
- liboqs-android/build.gradle
- site/build.gradle
- store/build.gradle
> Notifications no longer show on Android 13

- core/src/main/res/layout/content_anti_surveillance.xml
- core/src/main/res/layout/settings_section_advanced.xml
- core/src/main/res/layout/view_sliding_panel.xml
> AntiTracker in Play Store version

- core/src/main/java/net/ivpn/core/common/prefs/EncryptedSettingsPreference.kt
> Make crash logging option disabled by default

- core/src/main/java/net/ivpn/core/v2/viewmodel/AccountViewModel.kt
- core/src/main/res/layout/content_account.xml
> Disable active until for legacy accounts

- core/src/main/res/layout/view_sliding_panel.xml
> Small UI issue in the connection toggle

- core/src/main/java/net/ivpn/core/v2/viewmodel/SplitTunnelingViewModel.java
- core/src/main/res/layout/content_split_tunneling.xml
- core/src/main/res/values/strings.xml
> Split Tunneling for system-apps

- core/build.gradle
- fdroid/build.gradle
- fdroid/src/main/AndroidManifest.xml
- liboqs-android/build.gradle
- site/build.gradle
- store/build.gradle
> F-Droid v2.10.5 crashes on start

- core/src/main/java/net/ivpn/core/common/session/SessionController.kt
- core/src/main/java/net/ivpn/core/rest/requests/common/Request.java
> Increase session API calls timeout

- store/src/main/java/net/ivpn/client/billing/BillingActivity.java
- store/src/main/java/net/ivpn/client/billing/BillingManagerWrapper.java
- store/src/main/java/net/ivpn/client/billing/BillingNavigator.java
- store/src/main/java/net/ivpn/client/billing/BillingViewModel.java
- store/src/main/java/net/ivpn/client/signup/SignUpPeriodFragment.kt
- store/src/main/java/net/ivpn/client/signup/SignUpProductFragment.kt
- store/src/main/java/net/ivpn/client/signup/SignUpViewModel.kt
> Improve UX for pending payments

- core/src/main/AndroidManifest.xml
- fdroid/src/main/AndroidManifest.xml
> [F-Droid] Remove Sentry references

- .gitmodules
- core/build.gradle
- fdroid/build.gradle
- liboqs-android/build.gradle
- site/build.gradle
- store/build.gradle
> Remove support for Android 7.0 and older

- build.gradle
- core/build.gradle
- fdroid/build.gradle
- liboqs-android/build.gradle
- site/build.gradle
- store/build.gradle
> java.lang.RuntimeException: Unable to start activity

- core/src/main/res/values/strings.xml
> Split Tunnel INTERNET permission note

- core/src/main/AndroidManifest.xml
- site/src/main/AndroidManifest.xml
> Crash when Network Protection is engaged

- core/src/main/java/net/ivpn/core/common/prefs/ServersPreference.kt
> ServersPreference.setCurrentServer Exception:NoSuchElementException

- core/src/main/java/net/ivpn/core/common/tile/IVPNTileService.kt
> Impossible to enable the VPN from the shortcut/quickAccess bar

- site/src/main/java/net/ivpn/client/updates/UpdatesService.java
> Crash when using the 'Update' button

- core/src/main/res/values/strings.xml
Fix spelling of "Wi-Fi" and "Account ID"
Incorrect spelling
Correct spelling
> strings.xml: Fix spelling of "Wi-Fi" and "Account ID"
